spring.application.name=livraria-java

# Spring dev tools
spring.devtools.restart.enabled=true
logging.level.org.springframework=INFO

# Variáveis de ambiente
livraria.datasource.db_url=${DB_URL}
livraria.datasource.db_user=${DB_USER}
livraria.datasource.db_password=${DB_PASSWORD}